site:
  title: "Introducing llm-d: Your Production-Ready Path to Scalable LLM Inference"
  url: /
  start_page: modules:master:workshop/llm-d/00-index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/rh-one-2025/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ./content/supplemental-ui
    - path: ./content/lib
    - path: .nojekyll
    - path: ui.yml
      contents: "static_files: [ .nojekyll ]"

runtime:
  cache_dir: /tmp/.cache/antora

output:
  dir: ./www
  clean: true