site:
  title: "Introducing llm-d: Your Production-Ready Path to Scalable LLM Inference"
  # In the viewer, the internal URL should be root
  url: /
  # Fixed start_page syntax
  start_page: ROOT:index.adoc

content:
  sources:
    - url: .
      branches: HEAD

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/rh-one-2025/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ./content/supplemental-ui
    - path: ./content/lib
    - path: .nojekyll
    - path: ui.yml
      contents: "static_files: [ .nojekyll ]"

runtime:
  cache_dir: /tmp/.cache/antora

antora:
  extensions:
    - require: ./lib/dev-mode.js
      enabled: true

output:
  dir: ./www
  clean: true