---
showroom_namespace: "documentation"
showroom_app_name: "example-app"

showroom_git_repo: "https://github.com/rhpds/llm-d-showroom.git"
showroom_antora_image: "antora/antora:3.1.4"
showroom_nginx_image: "nginxinc/nginx-unprivileged:stable-alpine"