---
showroom_namespace: "documentation"
showroom_app_name: "example-app"

showroom_git_repo: "https://github.ibm.com/itz-content/deployer-openshift-showroom-example-webpage.git"
showroom_antora_image: "quay.io/ibmtz/openshift-showroom:latest"
